name: Test Pull Request

# test PR

on:
  pull_request:
    branches:
    - 'main'
    paths-ignore:
    - 'README.md'

jobs:
  test:
    runs-on: [self-hosted,Linux]
    steps:
    - run: echo "Hello world"
