name: Update README with system information

on:
  workflow_dispatch:
    inputs:
      system-url:
        description: 'System URL created by workflow'
        required: true

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: .
        commit_message: 'Updated system information'
        commit_user_name: 'GitHub Actions'
        commit_user_email: 'actions@github.com'
        keep_files: false
        allow_empty_commit: true
        push: false
        html_dir: .

    - name: Update system information in table
      run: |
        table="| Date | Actor | System URL |\\n| --- | --- | --- |\\n| $(date +%Y-%m-%d) | $GITHUB_ACTOR | ${{ github.event.inputs.system-url }} |\\n"
        sed -i "5i $table" README.md

    - name: Commit updated README
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update system information" -a

    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
